.safety:
  stage: security
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - pip3 install safety
  tags:
    - macos-local

Safety:
  extends: .safety
  script:
    - safety check -r requirements.txt --full-report

Safety stdin:
  extends: .safety
  script:
    - cat requirements.txt | safety check --stdin

Trivy:
  stage: security
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
    - apk -vv info|sort
    - trivy filesystem --exit-code 1 --skip-dirs /builds/gitlab-org-forks/ --cache-dir .trivycache/ /
  tags:
    - macos-local

Bandit:
  stage: security
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip3 install bandit
    - bandit -x $(pwd)/.venv/ -r $(pwd) -s B101
  tags:
    - macos-local

.docker_image_changes:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Dockerfile
        - requirements.txt
        - Pipfile
        - Pipfile.lock
        - .gitlab/.gitlab-ci.yml
        - .gitlab/build.yml
        - .gitlab/security.yml

.docker_scanner:
  stage: scan
  image: docker:git
  # Shared GitLab runners fallback:
  # services:
  #   - name: docker:dind
  #     alias: docker
  variables:
    DOCKER_BUILDKIT: "1"
    DOCKER_DRIVER: overlay2
    # Shared GitLab runners fallback:
    # DOCKER_TLS_CERTDIR: ""
    # DOCKER_HOST: "tcp://docker:2375"
    DOCKERFILE: "Dockerfile"
    DOCKERIMAGE: "$CI_REGISTRY_IMAGE:sha-$CI_COMMIT_SHORT_SHA"
    SHOWSTOPPER_PRIORITY: "CRITICAL"
    TRIVYCACHE: ".cache"
    ARTIFACT_FOLDER: "."
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  tags:
    - macos-local
  extends: .docker_image_changes

HadoLint:
  # Basic lint analysis of Dockerfile instructions
  extends: .docker_image_changes
  stage: scan
  image: docker:git
  variables:
    DOCKERFILE: "Dockerfile"
    ARTIFACT_FOLDER: "."

  after_script:
    - cat $ARTIFACT_FOLDER/hadolint_results.json

  script:
    - export VERSION=$(wget -q -O - https://api.github.com/repos/hadolint/hadolint/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget https://github.com/hadolint/hadolint/releases/download/v${VERSION}/hadolint-Linux-x86_64 && chmod +x hadolint-Linux-x86_64

    # NB: hadolint will always exit with 0 exit code
    - ./hadolint-Linux-x86_64 -f json $DOCKERFILE > $ARTIFACT_FOLDER/hadolint_results.json || exit 0

  artifacts:
    when: always # return artifacts even after job failure
    paths:
      - hadolint_results.json

Dockle:
  # Analysing best practices about docker image (users permissions, instructions followed when image was built, etc.)
  extends: .docker_scanner
  needs:
    - job: "Auto:docker:rebuild:test:publish"

  after_script:
    - cat $ARTIFACT_FOLDER/dockle_results.json

  script:
    - export VERSION=$(wget -q -O - https://api.github.com/repos/goodwithtech/dockle/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz && tar zxf dockle_${VERSION}_Linux-64bit.tar.gz
    - ./dockle --exit-code 1 --exit-level fatal -i DKL-DI-0004 -f json --output $ARTIFACT_FOLDER/dockle_results.json $DOCKERIMAGE

  artifacts:
    when: always # return artifacts even after job failure
    paths:
      - dockle_results.json

TrivyNice:
  # Analysing docker image and package dependencies against several CVE bases
  extends: .docker_scanner
  needs:
    - job: "Auto:docker:rebuild:test:publish"

  script:
    # getting the latest Trivy
    - apk add rpm
    - export VERSION=$(wget -q -O - https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz && tar zxf trivy_${VERSION}_Linux-64bit.tar.gz

    # displaying all vulnerabilities w/o failing the build
    - ./trivy image --cache-dir $TRIVYCACHE --format json --output $ARTIFACT_FOLDER/trivy_results.json --exit-code 0 $DOCKERIMAGE

    # write vulnerabilities info to stdout in human readable format (reading pure json is not fun, eh?). You can remove this if you don't need this.
    - ./trivy image --cache-dir $TRIVYCACHE --exit-code 0 $DOCKERIMAGE

    # failing the build if the SHOWSTOPPER priority is found
    - ./trivy image --cache-dir $TRIVYCACHE --exit-code 1 --severity $SHOWSTOPPER_PRIORITY --quiet $DOCKERIMAGE

  artifacts:
    when: always # return artifacts even after job failure
    paths:
      - trivy_results.json

  cache:
    paths:
      - .cache

Report:
  # combining tools outputs into one HTML
  stage: report
  extends: .docker_image_changes
  when: always
  image: python:3.14-alpine
  needs:
    - job: HadoLint
      artifacts: true
    - job: Dockle
      artifacts: true
    - job: TrivyNice
      artifacts: true

  script:
    - mkdir json
    - cp ./*.json ./json/
    - pip install json2html
    - wget https://raw.githubusercontent.com/shad0wrunner/docker_cicd/master/convert_json_results.py
    - python ./convert_json_results.py

  artifacts:
    paths:
      - results.html
