name: linters

on: [push, pull_request]

jobs:

  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: psf/black@stable
        with:
          version: "26.3.1"
          args: ". --diff"

  Pycodestyle:
    name: Lint Pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle $(pwd) --ignore=E501,W503 --exclude=.venv,venv

  Pycodestyle-full-report:
    name: Lint Pycodestyle Full Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pycodestyle Full Report
        run: |
          pip install pycodestyle
          pycodestyle $(pwd) --ignore=E501,W503 --exclude=.venv,venv
        continue-on-error: true

  Pylint:
    name: Lint Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pylint
        run: |
          pip install pylint==3.3.3
          touch __init__.py
          pylint $(pwd) --rcfile=.pylintrc --disable="$(cat .pylint-disabled-rules)" --ignore-patterns=.venv,venv
          rm __init__.py

  Pylint-full-report:
    name: Lint Pylint Full Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pylint Full Report
        run: |
          pip install pylint==3.3.3
          touch __init__.py
          pylint $(pwd) --rcfile=.pylintrc --disable="" --ignore-patterns=.venv,venv --exit-zero
          rm __init__.py
